[#18] Option to limit Slug Length
ctolkien/Slugify pull request #50
Opened 2022-10-01 07:46 UTC by ntbm

Added Option to Limit Output Slug Length.
Default Value is null to not introduce any breaking Changes into the Library.

2022-10-04 07:35 UTC, ctolkien requested changes
Nit: typo in comment

2022-10-04 07:35 UTC, ctolkien commented on README.md
> +// No Character limit to the slug lenght
```suggestion
// No Character limit to the slug length
```

2022-10-04 07:35 UTC, ctolkien commented
Hi @ntbm  - thanks for this!

2022-10-04 07:46 UTC, ctolkien commented
The failing test is an interesting one... normally the lib won't leave trailing -'s but we are specifically afking for a max length....

2022-10-04 15:11 UTC, ntbm commented
> The failing test is an interesting one... normally the lib won't leave trailing -'s but we are specifically afking for a max length.... 

That's why I added it. Handling all the specific edgescases will be a nightmare. So I'd vote to just accept that edge case. Question is if it be best to document it 🤔

2022-10-09 16:24 UTC, poke commented
Would it make sense to make the limiting a bit “smarter” so that it would not break within words if possible?

For example `"this is an example"` would slugify to `"this-is-an-example"`. But cutting it at 15 characters would result in `"this-is-an-exam"` which might not be ideal. Instead, there could be some more sophisticated limiting approach which would result in `"this-is-an"` instead since `example` doesn’t fit anymore.

2023-02-22 11:47 UTC, ctolkien commented
> Would it make sense to make the limiting a bit “smarter” so that it would not break within words if possible?

If there is a fast way of doing that? I imagine you need scan back to find the last non - character within the string limit length.

2025-03-18 10:53 UTC, ctolkien commented
Looping back around to this (only three years later...).. I think we should add this in, and simply perform an:
````
if limitingSlugLength then check end char and trim if a `-`
```

Will need to be re-implemented for v5 however.

2025-03-18 11:05 UTC, ctolkien commented
OK basically copy pasted to here:
https://github.com/ctolkien/Slugify/pull/151

@ntbm added you to the credits in the readme fwiw.

2025-03-18 11:05 UTC, closed without merging